version: "3.9"
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production

  # Optional MySQL setup (uncomment if using MySQL)
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: yourpassword
  #     MYSQL_DATABASE: taskdb
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
